name: CICD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_USERNAME: rajeshxdatascience
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT}}
        run: |
          dvc repro

      - name: Configure DagsHub DVC remote
        env:
          DAGSHUB_ACCESS_KEY: ${{ secrets.DAGSHUB_ACCESS_KEY }}
          DAGSHUB_SECRET_KEY: ${{ secrets.DAGSHUB_SECRET_KEY }}
        run: |
          dvc remote modify origin --local access_key_id "$DAGSHUB_ACCESS_KEY"
          dvc remote modify origin --local secret_access_key "$DAGSHUB_SECRET_KEY"

      - name: Push DVC data
        run: |
          dvc push

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changes to Git
        run: |
          git add .

      - name: Commit changes
        if: ${{ github.actor != 'github-actions[bot]' }}
        run: |
          git commit -m "Automated commit of DVC outputs and updated code" || echo "No changes to commit"

      - name: Push changes
        if: ${{ github.actor != 'github-actions[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ github.ref_name }}

      - name: Install test dependencies
        run: |
          pip install pytest

      - name: Run model loading test
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_USERNAME: rajeshxdatascience
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT}}
        run: |
          pytest scripts/test_load_model.py

      - name: Run model signature test
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_USERNAME: rajeshxdatascience
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT}}
        run: |
          pytest scripts/test_model_signature.py
      
      - name: Run model performance test
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_USERNAME: rajeshxdatascience
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT}}
        run: |
          pytest scripts/test_model_performance.py
      
      - name: Promote model to production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_USERNAME: rajeshxdatascience
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT}}
        run: python scripts/promote_model.py

      - name: Start FastAPI server
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_USERNAME: rajeshxdatascience
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m uvicorn app:app --host 0.0.0.0 --port 5000 > fastapi.log 2>&1 &
          sleep 15

          if ! curl --fail http://localhost:5000/; then
            cat fastapi.log
            exit 1
          fi

      - name: Run FastAPI tests
        run: |
          pytest scripts/test_fast_api.py
            